# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5qZr5rvbRIB0Weh5CER0w6hpzUgviyk
"""

from setuptools import setup

setup(
    name="my_custom_code",
    version='0.1',
    scripts=["predictor.py"])