# -*- coding: utf-8 -*-
"""setup.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1V5qZr5rvbRIB0Weh5CER0w6hpzUgviyk
"""

from setuptools import setup

setup(
    name="my_LSTM_code",
    version='0.2',
    install_requires = ['tensorflow-hub','seaborn','tensorflow>=1.7']
    scripts=["predictor_google_encoder.py","preprocess_google_encoder.py"])
